# -*- coding: utf-8 -*-
"""LangChain_(GeminiAPI).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XzkpmSRW4uPkpJw51bOQpOVqVuhdEPMa
"""

!pip install -qU "langchain[google-genai]"
!pip install google-ai-generativelanguage==0.6.15
!pip install -U langchain-google-genai`

import getpass
import os

if not os.environ.get("GOOGLE_API_KEY"):
  os.environ["GOOGLE_API_KEY"] = "AIzaSyDVsoMciy2Tmo72khNKFUcmSYgv5JW8frY"

from langchain.chat_models import init_chat_model

model = init_chat_model("gemini-2.0-flash", model_provider="google_genai")

model.invoke("who is prime minister of india")

from langchain_core.messages import HumanMessage, SystemMessage

messages = [
    SystemMessage("Translate the following from English into odia"),
    HumanMessage("how are you "),
]

model.invoke(messages)

model.invoke("Hello")

model.invoke([{"role": "user", "content": "Hello"}])

model.invoke([HumanMessage("Hello")])

"""# prompt templeate"""

from langchain_core.prompts import ChatPromptTemplate

system_template = "Translate the following from English into {language}"

prompt_template = ChatPromptTemplate.from_messages(
    [("system", system_template), ("user", "{text}")]
)

prompt = prompt_template.invoke({"language": "odia", "text": "how are you"})

prompt

prompt.to_messages()

response = model.invoke(prompt)
print(response.content)

