# -*- coding: utf-8 -*-
"""StableDiffusion_ImageGenModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Zz8c8EabTsoy1m8dqn5w-WjLso6at68

stabilityai/stable-diffusion-xl-base-1.0
"""

!nvidia-smi

!pip install diffusers --upgrade

!pip install invisible_watermark transformers accelerate safetensors

## BASE MODEL

from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, use_safetensors=True, variant="fp16")
pipe.to("cuda")

# if using torch < 2.0
# pipe.enable_xformers_memory_efficient_attention()

prompt = "A white persian cat playing with a woolen ball"

images = pipe(prompt=prompt).images[0]

images

import gradio as gr
from diffusers import StableDiffusionPipeline, EulerDiscreteScheduler
import torch

model_id = "stabilityai/stable-diffusion-xl-base-1.0"

scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = StableDiffusionPipeline.from_pretrained(model_id, scheduler=scheduler, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

def generated_image(prompt):
    image = pipe(prompt).images[0]
    return image

gr.Interface(
    fn=generated_image,
    inputs=gr.Textbox(label="Enter your prompt"),
    outputs=gr.Image(type="pil"),
    title="Stable Diffusion 2.1 - IMAGE GENERATOR APP",
    description="Enter text prompt and see the generated image"
).launch()

