# -*- coding: utf-8 -*-
"""StableDiffusion_AudioGenModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-xJAyLcQp32_P3dO39HJD2LdsJGtJvN

stabilityai/stable-audio-open-1.0
"""

!nvidia-smi

from huggingface_hub import notebook_login
notebook_login()

!pip install torchsde

!pip install -U diffusers

import torch
import soundfile as sf
from diffusers import StableAudioPipeline

pipe = StableAudioPipeline.from_pretrained("stabilityai/stable-audio-open-1.0", torch_dtype=torch.float16)
pipe = pipe.to("cuda")

# define the prompts
#prompt = "The sound of a hammer hitting a wooden surface."
prompt = " baby crying with louder noise"
negative_prompt = "Low quality."

# set the seed for generator
generator = torch.Generator("cuda").manual_seed(0)

# run the generation
audio = pipe(
    prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=200,
    audio_end_in_s=10.0,
    num_waveforms_per_prompt=3,
    generator=generator,
).audios

output = audio[0].T.float().cpu().numpy()
sf.write("baby crying with louder noise.wav", output, pipe.vae.sampling_rate)

output

