# -*- coding: utf-8 -*-
"""SmolAgents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwDgV1bwYBdt5cv5e3Ld9q8neEDINPCb
"""

#!pip install smolagents

import os
os.environ["HF_TOKEN"] = "your_api_key_here"

#!pip install duckduckgo-search
#!pip install smolagents[transformers]
#!pip install transformers
#!pip install ddgs

from smolagents import CodeAgent, DuckDuckGoSearchTool, TransformersModel

model = TransformersModel()
agent = CodeAgent(tools=[DuckDuckGoSearchTool()], model=model)

agent.run("differential human brain & machine brain")

from smolagents import ToolCallingAgent

tool_agent = ToolCallingAgent(tools=[DuckDuckGoSearchTool()], model = model)

tool_agent.run('agentic job market in 2025')

