# -*- coding: utf-8 -*-
"""LangChain_(withPrompt).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DrsmZgl6zNmBcBfH2Wq1JddHF8zQ2_-q
"""

import os
os.environ["GEMINI_API_KEY"] = "AIzaSyDPlcghP9LQQO6d9uj2s4TKa4jOSNgwxmM"

"""PROMPT TEMPLATE"""

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate.from_template("What is a good name for a company that makes {product}?")
prompt.format(product="colorful socks")

"""CHATPROMPT TEMPLATE"""

from langchain_core.prompts.chat import ChatPromptTemplate

template = "You are a helpful assistant that translates {input_language} to {output_language}."
human_template = "{text}"

chat_prompt = ChatPromptTemplate.from_messages([
    ("system", template),
    ("human", human_template),
])

chat_prompt.format_messages(input_language="English", output_language="French", text="I love programming.")

"""OUTPUT PARSER"""

from langchain.output_parsers import CommaSeparatedListOutputParser

output_parser = CommaSeparatedListOutputParser()
output_parser.parse("hi, bye")

from langchain import PromptTemplate

demo_template='''I want to suggest file IT return.
In an easy way, explain the basics of {financial_concept}.'''

prompt=PromptTemplate(
    input_variables=['financial_concept'],
    template=demo_template
    )

prompt.format(financial_concept='income tax')

